### ISSUE TITLE
Playback feature?

### ISSUE THREAD

**Issue by barryburd** [mattia-consiglio/VS-Code-Recorder#1]
Hi Mattia,
I'm trying to have students send me a record of their coding steps (so I can see their thinking process and make sure they didn't just paste code from elsewhere). vs-code-recorder would be great for this, but it would be even better if there was a way to play back a recorded session. Is that feasible?
  --Barry

**Comment by mattia-consiglio** [comment]
Hi Barry,

It's in my intention to create a web player. When it's ready, I'll link it in the extension README.md.
